{
 "title": "User API metrics",
 "time": { "from": "2024-07-11T22:50:00.000Z", "to": "2024-07-11T23:20:59.000Z" },
 "templating": {
  "list": [
   {
    "name": "quantile",
    "label": "Quantile",
    "query": "max : 1, 0.99, 0.95, 0.9, 0.8, 0.75, 0.5"
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(jvm_memory_used_bytes,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "system_cpu_usage{instance='$instance'}",
     "legendFormat": "system {{instance}}"
    },
    {
     "expr": "process_cpu_usage{instance='$instance'}",
     "legendFormat": "process {{instance}}"
    }
   ]
  },
  {
   "title": "JVM memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (jvm_memory_used_bytes{instance='$instance'})",
     "legendFormat": "used {{pod}}"
    },
    {
     "expr": "sum by (pod) (jvm_memory_committed_bytes{instance='$instance'})",
     "legendFormat": "committed {{pod}}"
    },
    {
     "expr": "sum by (pod) (jvm_memory_max_bytes{instance='$instance'})",
     "legendFormat": "max {{pod}}"
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (uri) (rate(http_server_requests_seconds_count{uri=~'/dumb/.*'}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency (response time)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, sum by(le, uri) (rate(http_server_requests_seconds_bucket{uri=~\"/dumb/.*\"}[2m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error 5xx rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum by (uri) (rate(http_server_requests_seconds_count{uri=~'/dumb/.*',status=~\"5.+\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}