spring:
  application.name: users
  jpa:
    generate-ddl: true
    properties.hibernate.default_schema: ${postgres_default_schema}
  datasource:
    url: jdbc:postgresql://${postgres_url}/${postgres_database}?currentSchema=${spring.jpa.properties.hibernate.default_schema}
    driver-class-name: org.postgresql.Driver
    username: ${postgres_username}
    password: ${postgres_password}

