openapi: 3.0.3
info:
  version: 1.0.1
  title: checkout-service
  description: checkout-service

servers:
  - url: '{schema}://arch.homework/api/checkoutservice'
    variables:
      schema:
        enum:
          - http
          - https
        default: http

paths:
  /private/account:
    post:
      tags:
        - checkout
        - private
      summary: Создание счета покупателя.
      description: Создание счета покупателя.
      operationId: createAccount
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountDto'
      responses:
        '201':
          description: Счет создан.
  /private/account/replenishment:
    post:
      tags:
        - checkout
        - private
      summary: Пополнение счета пользователя.
      description: Пополнение счета пользователя.
      operationId: replenishAccount
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountReplenishmentDto'
      responses:
        '200':
          description: Счет пополнен.
          content:
            application/json:
              schema:
                type: string
                description: Идентификатор пополнения
                format: uuid
  /private/order-payment:
    post:
      tags:
        - checkout
        - private
      summary: Оплата заказа.
      description: Оплата заказа.
      operationId: createOrderPayment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderPaymentDto'
      responses:
        '200':
          description: Оплата заказа проведена.
          content:
            application/json:
              schema:
                type: string
                description: Идентификатор платежа
                format: uuid
        '400':
          description: Оплата заказа не проведена.
          content:
            application/json:
              schema:
                type: string
                description: Код ошибки
  /public/account:
    get:
      tags:
        - checkout
        - public
      summary: Счет покупателя.
      description: Получить счет покупателя
      operationId: getAccount
      parameters:
        - name: customer_id
          description: Идентификатор покупателя
          in: query
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Счет покупателя
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountDto'
components:
  schemas:
    AccountDto:
      description: Счет
      type: object
      properties:
        customer_id:
          type: string
          format: uuid
          description: Идентификатор покупателя
        balance:
          type: number
          description: Остаток на счете
    OrderPaymentDto:
      description: Оплата заказа
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Идентификатор платежа
        customer_id:
          type: string
          format: uuid
          description: Идентификатор покупателя
        order_id:
          type: string
          format: uuid
          description: Идентификатор заказа
        amout:
          type: number
          description: Сумма платежа
    AccountReplenishmentDto:
      description: Пополнение счета покупателя
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Идентификатор пополнения
        customer_id:
          type: string
          format: uuid
          description: Идентификатор покупателя
        amount:
          type: number
          description: Сумма пополнения