spring:
  application.name: stockservice
  jpa:
    generate-ddl: true
    properties.hibernate.default_schema: ${spring.application.name}
  datasource:
    url: jdbc:postgresql://${postgres_url}/${postgres_database}?currentSchema=${spring.jpa.properties.hibernate.default_schema}
    driver-class-name: org.postgresql.Driver
    username: ${postgres_username}
    password: ${postgres_password}
  kafka:
    bootstrap-servers: ${kafka_servers}
    topic: ${products_topic}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
server:
  servlet:
    context-path: /api/stockservice
management:
  endpoint.health:
    cache.time-to-live: 20s
    show-details: always
    group:
      readiness:
        include: ping
      liveness:
        include: diskSpace
  endpoints.web.exposure.include: info, health, prometheus
  metrics:
    enable:
      jvm: true
      system: true
      tomcat: true
    tags:
      application: ${spring.application.name}
    distribution:
      slo:
        http.server.requests: 10ms, 50ms, 100ms, 200ms, 300ms, 400ms, 500ms, 600ms, 800ms
order.url: orderservice:8080/api/orderservice
delivery.url: deliveryservice:8080/api/deliveryservice
logging:
  level.homework.arch: DEBUG
  file.name: /var/log/application/application_${POD_NAME}.log
spring.cloud.discovery.client.composite-indicator.enabled: false
spring.jackson.default-property-inclusion: NON_NULL
