server.port: 8083
logging.level.homework.arch: DEBUG
cartReserveMinutes: 2
spring.kafka.bootstrap-servers: localhost:9092
order.url: localhost:8085/api/orderservice
delivery.url: localhost:8087/api/deliveryservice