spring:
  application.name: productservice
  kafka:
    bootstrap-servers: ${kafka_servers}
    topic: ${products_topic}
    consumer:
      group-id: ${spring.application.name}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.value.default.type: homework.arch.productservice.kafka.ProductKafkaDto
server:
  servlet:
    context-path: /api/productservice
management:
  endpoint.health:
    cache.time-to-live: 20s
    show-details: always
    group:
      readiness:
        include: ping
      liveness:
        include: diskSpace
  endpoints.web.exposure.include: info, health, prometheus
  metrics:
    enable:
      jvm: true
      system: true
      tomcat: true
    tags:
      application: ${spring.application.name}
    distribution:
      slo:
        http.server.requests: 10ms, 50ms, 100ms, 200ms, 300ms, 400ms, 500ms, 600ms, 800ms
logging:
  level.homework.arch: DEBUG
  file.name: /var/log/application/application.log
spring.cloud.discovery.client.composite-indicator.enabled: false
spring.jackson.default-property-inclusion: NON_NULL
