openapi: 3.0.3
info:
  version: 2.0.0
  title: Checkout service
  description: Подтверждение заказа

servers:
  - url: '{schema}://arch.homework/api/checkoutservice'
    variables:
      schema:
        enum:
          - http
          - https
        default: http
tags:
  - name: public
    description: API, доступный пользователям
  - name: external
    description: API для интеграции с внешними системами

paths:
  /public/checkout:
    post:
      tags:
        - checkout
        - public
      summary: Оформить заказ.
      description: Оформить заказ.
      operationId: checkout
      parameters:
        - name: "Idempotency-Key"
          in: header
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CheckoutDto'
      responses:
        '200':
          description: Начато оформление заказа
          content:
            application/json:
              schema:
                type: object
                properties:
                  paymentSystemRef:
                    type: string
                    format: url
                    description: Ссылка для выполнения платежа в платежной системе
                  payment:
                    $ref: '#/components/schemas/PaymentDto'
  /external/payment/{id}/confirmation:
    post:
      tags:
        - checkout
        - external
      summary: Подтвердить выполнение платежа по заказу.
      description: Подтвердить выполнение платежа по заказу.
      operationId: confirmPayment
      parameters:
        - name: id
          description: Идентификатор платежа
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentConfirmationDto'
      responses:
        '200':
          description: Подтверждение принято
components:
  schemas:
    CheckoutDto:
      description: Запрос оформления заказа
      type: object
      properties:
        paymentWay:
          $ref: '#/components/schemas/PaymentWayDto'
        deliveryAddress:
          $ref: '#/components/schemas/DeliveryAddressDto'
    PaymentWayDto:
      description: Способ оплаты
      type: object
      required:
        - type
      properties:
        type:
          type: string
          enum:
            - CARD
    DeliveryAddressDto:
      description: Адрес доставки
      type: object
      properties:
        asText:
          type: string
          description: Текстовое представление адреса
    PaymentDto:
      description: Информация об оплате заказа
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Идентификатор платежа
        status:
          $ref: '#/components/schemas/PaymentStatusDto'
        paymentWay:
          $ref: '#/components/schemas/PaymentWayDto'
    PaymentStatusDto:
      description: Статус платежа
      type: string
      enum:
        - PENDING
        - DONE
        - FAILED
    PaymentConfirmationDto:
      description: Подтверждение платежа
      type: object
      properties:
        paymentStatus:
          type: string
          enum:
            - PROCESSED
            - FAILED
