apiVersion: v1
kind: ConfigMap
metadata:
  name: common-configs
data:
  kafka_servers: "u59-kafka.lan:9092"
  products_topic: "products_v1"
  postgres_url: "u59-postgresql.lan:5432"
  postgres_database: "develop"
  postgres_username: "dev_user"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-configmap
data:
  promtail-config.yaml: |
    clients:
      - url: http://u59-loki320.lan:3100/loki/api/v1/push
        external_labels:
          application: otus
          env: ${POD_NAMESPACE}
          service: ${SERVICE_NAME}
          pod_name: ${POD_NAME}
    scrape_configs:
      - job_name: "otus_${POD_NAMESPACE}_${POD_NAME}"
        static_configs:
          - targets:
              - localhost
            labels:
              __path__: /var/log/application/application_${POD_NAME}.log
