spring:
  application.name: authservice
management:
  endpoint.health:
    cache.time-to-live: 20s
    show-details: always
    group:
      readiness:
        include: ping
      liveness:
        include: diskSpace
  endpoints.web.exposure.include: info, health, prometheus
  metrics:
    enable:
      jvm: true
      system: true
      tomcat: true
    tags:
      application: ${spring.application.name}
    distribution:
      slo:
        http.server.requests: 10ms, 50ms, 100ms, 200ms, 300ms, 400ms, 500ms, 600ms, 800ms
profile-service-url: http://profileservice:8080
logging.level.homework.arch: DEBUG
logging.level.org.springframework.web.client: DEBUG